import { Subject } from "@/types";

const SUBJECT_CATALOG = [
  [1, "CS101", "Introduction to Programming", "Computer Science"],
  [2, "CS102", "Data Structures", "Computer Science"],
  [3, "CS103", "Algorithms", "Computer Science"],
  [4, "CS104", "Computer Systems", "Computer Science"],
  [5, "CS105", "Database Systems", "Computer Science"],
  [6, "CS106", "Web Development", "Computer Science"],
  [7, "CS107", "Software Engineering", "Computer Science"],
  [8, "CS108", "Operating Systems", "Computer Science"],
  [9, "CS109", "Computer Networks", "Computer Science"],
  [10, "CS110", "Artificial Intelligence", "Computer Science"],
  [11, "CS111", "Machine Learning", "Computer Science"],
  [12, "CS112", "Mobile App Development", "Computer Science"],
  [13, "MATH101", "Calculus I", "Mathematics"],
  [14, "MATH102", "Calculus II", "Mathematics"],
  [15, "MATH103", "Linear Algebra", "Mathematics"],
  [16, "MATH104", "Discrete Mathematics", "Mathematics"],
  [17, "MATH105", "Differential Equations", "Mathematics"],
  [18, "MATH106", "Probability Theory", "Mathematics"],
  [19, "MATH107", "Numerical Methods", "Mathematics"],
  [20, "MATH108", "Abstract Algebra", "Mathematics"],
  [21, "MATH109", "Real Analysis", "Mathematics"],
  [22, "MATH110", "Applied Statistics", "Mathematics"],
  [23, "PHYS101", "Classical Mechanics", "Physics"],
  [24, "PHYS102", "Electromagnetism", "Physics"],
  [25, "PHYS103", "Waves and Optics", "Physics"],
  [26, "PHYS104", "Thermodynamics", "Physics"],
  [27, "PHYS105", "Modern Physics", "Physics"],
  [28, "PHYS106", "Quantum Physics", "Physics"],
  [29, "PHYS107", "Astrophysics", "Physics"],
  [30, "PHYS108", "Laboratory Physics", "Physics"],
  [31, "CHEM101", "General Chemistry", "Chemistry"],
  [32, "CHEM102", "Organic Chemistry", "Chemistry"],
  [33, "CHEM103", "Inorganic Chemistry", "Chemistry"],
  [34, "CHEM104", "Physical Chemistry", "Chemistry"],
  [35, "CHEM105", "Analytical Chemistry", "Chemistry"],
  [36, "CHEM106", "Biochemistry", "Chemistry"],
  [37, "CHEM107", "Environmental Chemistry", "Chemistry"],
  [38, "CHEM108", "Instrumental Analysis", "Chemistry"],
  [39, "BIO101", "Cell Biology", "Biological Sciences"],
  [40, "BIO102", "Genetics", "Biological Sciences"],
  [41, "BIO103", "Microbiology", "Biological Sciences"],
  [42, "BIO104", "Human Anatomy", "Biological Sciences"],
  [43, "BIO105", "Physiology", "Biological Sciences"],
  [44, "BIO106", "Ecology", "Biological Sciences"],
  [45, "BIO107", "Molecular Biology", "Biological Sciences"],
  [46, "BIO108", "Biotechnology", "Biological Sciences"],
  [47, "ECON101", "Microeconomics", "Economics"],
  [48, "ECON102", "Macroeconomics", "Economics"],
  [49, "ECON103", "Econometrics", "Economics"],
  [50, "ECON104", "Public Finance", "Economics"],
  [51, "ECON105", "Development Economics", "Economics"],
  [52, "ECON106", "International Economics", "Economics"],
  [53, "ECON107", "Labor Economics", "Economics"],
  [54, "ECON108", "Money and Banking", "Economics"],
  [55, "PSY101", "Introduction to Psychology", "Psychology"],
  [56, "PSY102", "Cognitive Psychology", "Psychology"],
  [57, "PSY103", "Developmental Psychology", "Psychology"],
  [58, "PSY104", "Social Psychology", "Psychology"],
  [59, "PSY105", "Abnormal Psychology", "Psychology"],
  [60, "PSY106", "Research Methods in Psychology", "Psychology"],
  [61, "PSY107", "Behavioral Neuroscience", "Psychology"],
  [62, "PSY108", "Counseling Psychology", "Psychology"],
  [63, "HIST101", "World History", "History"],
  [64, "HIST102", "Ancient Civilizations", "History"],
  [65, "HIST103", "Medieval History", "History"],
  [66, "HIST104", "Modern European History", "History"],
  [67, "HIST105", "African History", "History"],
  [68, "HIST106", "Asian History", "History"],
  [69, "HIST107", "History of Science", "History"],
  [70, "ENG101", "Academic Writing", "English"],
  [71, "ENG102", "Literary Analysis", "English"],
  [72, "ENG103", "World Literature", "English"],
  [73, "ENG104", "Creative Writing", "English"],
  [74, "ENG105", "Linguistics", "English"],
  [75, "ENG106", "Professional Communication", "English"],
  [76, "PHIL101", "Introduction to Philosophy", "Philosophy"],
  [77, "PHIL102", "Ethics", "Philosophy"],
  [78, "PHIL103", "Logic", "Philosophy"],
  [79, "PHIL104", "Political Philosophy", "Philosophy"],
  [80, "PHIL105", "Philosophy of Mind", "Philosophy"],
  [81, "PHIL106", "Aesthetics", "Philosophy"],
  [82, "BUS101", "Principles of Management", "Business Administration"],
  [83, "BUS102", "Marketing Fundamentals", "Business Administration"],
  [84, "BUS103", "Financial Accounting", "Business Administration"],
  [85, "BUS104", "Business Communication", "Business Administration"],
  [86, "BUS105", "Organizational Behavior", "Business Administration"],
  [87, "BUS106", "Entrepreneurship", "Business Administration"],
  [88, "BUS107", "Strategic Management", "Business Administration"],
  [89, "BUS108", "Operations Management", "Business Administration"],
  [90, "ART101", "Drawing Fundamentals", "Visual Arts"],
  [91, "ART102", "Color Theory", "Visual Arts"],
  [92, "ART103", "Digital Illustration", "Visual Arts"],
  [93, "ART104", "Art History", "Visual Arts"],
] as const;

const buildDescription = (name: string, department: string) =>
  `A concise overview of ${name.toLowerCase()} in the ${department.toLowerCase()} curriculum.`;

const buildCreatedAt = (id: number) => {
  const day = ((id - 1) % 28) + 1;

  return new Date(2025, 0, day).toISOString();
};

export const mockSubjects: Subject[] = SUBJECT_CATALOG.map(([id, code, name, department]) => ({
  id,
  code,
  name,
  department,
  description: buildDescription(name, department),
  createdAt: buildCreatedAt(id),
}));