export const DEPARTMENTS = [
  'Accounting',
  'Actuarial Science',
  'Aerospace Engineering',
  'Agricultural Engineering',
  'Agricultural Science',
  'Anthropology',
  'Applied Mathematics',
  'Architecture',
  'Art History',
  'Artificial Intelligence',
  'Astronomy',
  'Biochemistry',
  'Bioinformatics',
  'Biological Sciences',
  'Biomedical Engineering',
  'Biotechnology',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Clinical Psychology',
  'Communication',
  'Communication Engineering',
  'Computer Engineering',
  'Computer Science',
  'Criminology',
  'Cybersecurity',
  'Data Science',
  'Dentistry',
  'Design',
  'Economics',
  'Education',
  'Electrical Engineering',
  'Electronics Engineering',
  'Energy Engineering',
  'English',
  'Environmental Engineering',
  'Environmental Science',
  'Finance',
  'Fine Arts',
  'Food Engineering',
  'Forensic Science',
  'Genetics',
  'Geography',
  'Geology',
  'Graphic Design',
  'Health Informatics',
  'History',
  'Hospitality Management',
  'Human Resource Management',
  'Industrial Engineering',
  'Information Systems',
  'Information Technology',
  'International Business',
  'International Relations',
  'Islamic Studies',
  'Journalism',
  'Law',
  'Library and Information Science',
  'Linguistics',
  'Management',
  'Marine Engineering',
  'Marketing',
  'Materials Science and Engineering',
  'Mathematics',
  'Mechanical Engineering',
  'Mechatronics Engineering',
  'Media Studies',
  'Medicine',
  'Microbiology',
  'Music',
  'Nanotechnology',
  'Neuroscience',
  'Nursing',
  'Nutrition and Dietetics',
  'Petroleum Engineering',
  'Pharmacy',
  'Philosophy',
  'Physics',
  'Physiotherapy',
  'Political Science',
  'Psychology',
  'Public Administration',
  'Public Health',
  'Robotics Engineering',
  'Software Engineering',
  'Sociology',
  'Statistics',
  'Supply Chain Management',
  'Textile Engineering',
  'Urban and Regional Planning',
  'Veterinary Medicine',
  'Visual Arts'
];

export const DEAPARTMENT_OPTIONS = DEPARTMENTS.map((department) => ({
  value: department,
  label: department,
}));